# Generated by Django 6.0.3 on 2026-04-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_imagemproduto_mensagemchat_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
